-- MySQL Script generated by MySQL Workbench
-- Tue Mar 16 01:08:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Private_Research
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Private_Research
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Private_Research` DEFAULT CHARACTER SET utf8 ;
USE `Private_Research` ;

-- -----------------------------------------------------
-- Table `Private_Research`.`Person-Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Private_Research`.`Person-Company` (
  `Name` VARCHAR(90) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Phone` INT NOT NULL,
  `Email` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Name`, `Address`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Private_Research`.`Reasearch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Private_Research`.`Reasearch` (
  `idReasearch` INT NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Start_Date` DATE NOT NULL,
  `End_Date` DATE NOT NULL,
  `Budget` INT NOT NULL,
  `Person-Company_Name` VARCHAR(90) NOT NULL,
  `Person-Company_Address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idReasearch`),
  INDEX `fk_Reasearch_Person-Company_idx` (`Person-Company_Name` ASC, `Person-Company_Address` ASC) VISIBLE,
  CONSTRAINT `fk_Reasearch_Person-Company`
    FOREIGN KEY (`Person-Company_Name` , `Person-Company_Address`)
    REFERENCES `Private_Research`.`Person-Company` (`Name` , `Address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Private_Research`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Private_Research`.`Employee` (
  `id_Number` INT NOT NULL,
  `AFM` INT NOT NULL,
  `Name` VARCHAR(90) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Phone` INT NOT NULL,
  `Date_Of_Birth` DATE NOT NULL,
  `Reasearch_idReasearch` INT NOT NULL,
  PRIMARY KEY (`id_Number`),
  INDEX `fk_Employee_Reasearch1_idx` (`Reasearch_idReasearch` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Reasearch1`
    FOREIGN KEY (`Reasearch_idReasearch`)
    REFERENCES `Private_Research`.`Reasearch` (`idReasearch`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
