-- MySQL Script generated by MySQL Workbench
-- Thu Apr  1 00:25:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airport` (
  `idAirport` INT NOT NULL,
  `Name` VARCHAR(60) NOT NULL,
  `City` VARCHAR(60) NOT NULL,
  `Country` VARCHAR(60) NOT NULL,
  `NPA` INT NOT NULL,
  PRIMARY KEY (`idAirport`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Model` (
  `idModel` VARCHAR(45) NOT NULL,
  `Capacity` INT NOT NULL,
  `Weight` INT NOT NULL,
  PRIMARY KEY (`idModel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Airplane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Airplane` (
  `idAirplane` INT NOT NULL,
  `Model_idModel` VARCHAR(45) NOT NULL,
  `Airport_idAirport` INT NOT NULL,
  PRIMARY KEY (`idAirplane`, `Airport_idAirport`),
  INDEX `fk_Airplane_Model_idx` (`Model_idModel` ASC) VISIBLE,
  INDEX `fk_Airplane_Airport1_idx` (`Airport_idAirport` ASC) VISIBLE,
  CONSTRAINT `fk_Airplane_Model`
    FOREIGN KEY (`Model_idModel`)
    REFERENCES `mydb`.`Model` (`idModel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Airplane_Airport1`
    FOREIGN KEY (`Airport_idAirport`)
    REFERENCES `mydb`.`Airport` (`idAirport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Union`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Union` (
  `Name` VARCHAR(60) NOT NULL,
  `EstablishmentYear` INT NOT NULL,
  PRIMARY KEY (`Name`, `EstablishmentYear`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Technician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Technician` (
  `idTechnician` INT NOT NULL,
  `Name` VARCHAR(60) NOT NULL,
  `Address` VARCHAR(60) NOT NULL,
  `Telephone` INT NOT NULL,
  `Salary` INT NOT NULL,
  `Union_Name` VARCHAR(60) NOT NULL,
  `Union_EstablishmentYear` INT NOT NULL,
  PRIMARY KEY (`idTechnician`, `Union_Name`, `Union_EstablishmentYear`),
  INDEX `fk_Technician_Union1_idx` (`Union_Name` ASC, `Union_EstablishmentYear` ASC) VISIBLE,
  CONSTRAINT `fk_Technician_Union1`
    FOREIGN KEY (`Union_Name` , `Union_EstablishmentYear`)
    REFERENCES `mydb`.`Union` (`Name` , `EstablishmentYear`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Controller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Controller` (
  `Name` VARCHAR(60) NOT NULL,
  `ADT` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(60) NOT NULL,
  `DateOfCheck` DATE NULL,
  `Union_Name` VARCHAR(60) NOT NULL,
  `Union_EstablishmentYear` INT NOT NULL,
  PRIMARY KEY (`ADT`, `Union_Name`, `Union_EstablishmentYear`),
  INDEX `fk_Controller_Union1_idx` (`Union_Name` ASC, `Union_EstablishmentYear` ASC) VISIBLE,
  CONSTRAINT `fk_Controller_Union1`
    FOREIGN KEY (`Union_Name` , `Union_EstablishmentYear`)
    REFERENCES `mydb`.`Union` (`Name` , `EstablishmentYear`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Check`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Check` (
  `YPA` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(60) NOT NULL,
  `MaxGrade` INT NOT NULL,
  PRIMARY KEY (`YPA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Company` (
  `idCompany` INT NOT NULL,
  `Name` VARCHAR(60) NOT NULL,
  `Country` VARCHAR(60) NOT NULL,
  `NationalCode` INT NOT NULL,
  `Active` TINYINT NOT NULL,
  PRIMARY KEY (`idCompany`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Schedule` (
  `idSchedule` INT NOT NULL,
  `Company_idCompany` INT NOT NULL,
  `Airport_idAirport` INT NOT NULL,
  `DestinationAiport_id` INT NOT NULL,
  PRIMARY KEY (`idSchedule`, `Company_idCompany`, `Airport_idAirport`, `DestinationAiport_id`),
  INDEX `fk_Schedule_Company1_idx` (`Company_idCompany` ASC) VISIBLE,
  INDEX `fk_Schedule_Airport1_idx` (`Airport_idAirport` ASC) VISIBLE,
  CONSTRAINT `fk_Schedule_Company1`
    FOREIGN KEY (`Company_idCompany`)
    REFERENCES `mydb`.`Company` (`idCompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Schedule_Airport1`
    FOREIGN KEY (`Airport_idAirport`)
    REFERENCES `mydb`.`Airport` (`idAirport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Technician_has_Model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Technician_has_Model` (
  `Technician_idTechnician` INT NOT NULL,
  `Model_idModel` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Technician_idTechnician`, `Model_idModel`),
  INDEX `fk_Technician_has_Model_Model1_idx` (`Model_idModel` ASC) VISIBLE,
  INDEX `fk_Technician_has_Model_Technician1_idx` (`Technician_idTechnician` ASC) VISIBLE,
  CONSTRAINT `fk_Technician_has_Model_Technician1`
    FOREIGN KEY (`Technician_idTechnician`)
    REFERENCES `mydb`.`Technician` (`idTechnician`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Technician_has_Model_Model1`
    FOREIGN KEY (`Model_idModel`)
    REFERENCES `mydb`.`Model` (`idModel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Controller_has_Airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Controller_has_Airport` (
  `Controller_ADT` VARCHAR(45) NOT NULL,
  `Airport_idAirport` INT NOT NULL,
  PRIMARY KEY (`Controller_ADT`, `Airport_idAirport`),
  INDEX `fk_Controller_has_Airport_Airport1_idx` (`Airport_idAirport` ASC) VISIBLE,
  INDEX `fk_Controller_has_Airport_Controller1_idx` (`Controller_ADT` ASC) VISIBLE,
  CONSTRAINT `fk_Controller_has_Airport_Controller1`
    FOREIGN KEY (`Controller_ADT`)
    REFERENCES `mydb`.`Controller` (`ADT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Controller_has_Airport_Airport1`
    FOREIGN KEY (`Airport_idAirport`)
    REFERENCES `mydb`.`Airport` (`idAirport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Check_has_Airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Check_has_Airport` (
  `Check_YPA` VARCHAR(45) NOT NULL,
  `Airport_idAirport` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Hours` INT NOT NULL,
  `Grade` INT NOT NULL,
  PRIMARY KEY (`Check_YPA`, `Airport_idAirport`),
  INDEX `fk_Check_has_Airport_Airport1_idx` (`Airport_idAirport` ASC) VISIBLE,
  INDEX `fk_Check_has_Airport_Check1_idx` (`Check_YPA` ASC) VISIBLE,
  CONSTRAINT `fk_Check_has_Airport_Check1`
    FOREIGN KEY (`Check_YPA`)
    REFERENCES `mydb`.`Check` (`YPA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Check_has_Airport_Airport1`
    FOREIGN KEY (`Airport_idAirport`)
    REFERENCES `mydb`.`Airport` (`idAirport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
